# Generated by Django 2.2.2 on 2019-06-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_excursioninbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursioninbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
